"""Toy graph/profile tools for the ECCB 2026 LLM agent practical.

Toy implementations entirely generated by Claude!!
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import networkx as nx


@dataclass(frozen=True)
class ProfileFeature:
    feature_id: str
    score: float


def build_toy_graph() -> nx.MultiDiGraph:
    """Create a small biomedical knowledge graph for early tutorial testing."""
    graph = nx.MultiDiGraph()

    graph.add_node("HP:0000729", name="Autism spectrum disorder", type="phenotype")
    graph.add_node("GENE:SHANK3", name="SHANK3", type="gene")
    graph.add_node("GENE:CHD8", name="CHD8", type="gene")
    graph.add_node("GENE:SCN2A", name="SCN2A", type="gene")
    graph.add_node("PATHWAY:SYNAPSE", name="Synaptic signalling", type="pathway")
    graph.add_node("PATHWAY:CHROMATIN", name="Chromatin regulation", type="pathway")

    graph.add_edge(
        "GENE:SHANK3",
        "HP:0000729",
        relation="associated_with",
        evidence="toy literature edge",
    )
    graph.add_edge(
        "GENE:CHD8",
        "HP:0000729",
        relation="associated_with",
        evidence="toy literature edge",
    )
    graph.add_edge(
        "GENE:SCN2A",
        "HP:0000729",
        relation="associated_with",
        evidence="toy literature edge",
    )
    graph.add_edge("GENE:SHANK3", "PATHWAY:SYNAPSE", relation="participates_in")
    graph.add_edge("GENE:SCN2A", "PATHWAY:SYNAPSE", relation="participates_in")
    graph.add_edge("GENE:CHD8", "PATHWAY:CHROMATIN", relation="participates_in")

    return graph


TOY_PROFILES: dict[str, list[ProfileFeature]] = {
    "P001": [
        ProfileFeature("GENE:SHANK3", 2.4),
        ProfileFeature("GENE:SCN2A", 1.7),
        ProfileFeature("GENE:CHD8", 0.8),
    ],
    "P002": [
        ProfileFeature("GENE:CHD8", 2.1),
        ProfileFeature("GENE:SCN2A", 1.1),
        ProfileFeature("GENE:SHANK3", 0.5),
    ],
}


def search_nodes(graph: nx.MultiDiGraph, query: str) -> list[dict[str, Any]]:
    """Return nodes whose ID or name contains the query string."""
    query_lower = query.lower()
    matches = []
    for node_id, attrs in graph.nodes(data=True):
        name = str(attrs.get("name", ""))
        if query_lower in node_id.lower() or query_lower in name.lower():
            matches.append({"node_id": node_id, **attrs})
    return matches


def get_neighbors(
    graph: nx.MultiDiGraph,
    node_id: str,
    node_type: str | None = None,
) -> list[dict[str, Any]]:
    """Return incoming and outgoing neighbors with edge metadata."""
    if node_id not in graph:
        return []

    neighbors: list[dict[str, Any]] = []

    for source, target, edge_attrs in graph.in_edges(node_id, data=True):
        attrs = graph.nodes[source]
        if node_type is None or attrs.get("type") == node_type:
            neighbors.append(
                {
                    "node_id": source,
                    "direction": "incoming",
                    "edge_to": target,
                    "node": dict(attrs),
                    "edge": dict(edge_attrs),
                }
            )

    for source, target, edge_attrs in graph.out_edges(node_id, data=True):
        attrs = graph.nodes[target]
        if node_type is None or attrs.get("type") == node_type:
            neighbors.append(
                {
                    "node_id": target,
                    "direction": "outgoing",
                    "edge_from": source,
                    "node": dict(attrs),
                    "edge": dict(edge_attrs),
                }
            )

    return neighbors


def rank_profile_features(profile_id: str, top_n: int = 20) -> list[dict[str, Any]]:
    """Return top molecular features for a toy profile."""
    features = TOY_PROFILES.get(profile_id, [])
    ranked = sorted(features, key=lambda feature: feature.score, reverse=True)
    return [
        {"feature_id": feature.feature_id, "score": feature.score}
        for feature in ranked[:top_n]
    ]


def rank_candidate_genes(
    graph: nx.MultiDiGraph,
    profile_id: str,
    phenotype_id: str,
) -> list[dict[str, Any]]:
    """Rank phenotype-linked genes by profile score."""
    phenotype_genes = {
        item["node_id"]
        for item in get_neighbors(graph, phenotype_id, node_type="gene")
    }
    profile_scores = {
        item["feature_id"]: item["score"]
        for item in rank_profile_features(profile_id)
    }

    ranked = []
    for gene_id in phenotype_genes:
        if gene_id in profile_scores:
            ranked.append(
                {
                    "gene_id": gene_id,
                    "name": graph.nodes[gene_id].get("name", gene_id),
                    "profile_score": profile_scores[gene_id],
                    "phenotype_id": phenotype_id,
                }
            )

    return sorted(ranked, key=lambda item: item["profile_score"], reverse=True)

